### ISSUE TITLE
Using the <said> tag

### ISSUE THREAD

**Issue by RobbKH** [SASDigitalHumanitiesTraining/TextEncoding#13]
Should quotation marks in the content be removed when using `<said></said>`?

"Everyone should learn TEI"

becomes

`<said>`Everyone should learn TEI`</said>`

**Comment by cmohge1** [comment]
Have a look at the TEI Guidelines: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COHQQ

Yes, the quote marks would not be included if you use `<said>` or `<q>` -- just make sure you have a sense of whether `<said>` or `<q>` is appropriate. They mean slightly different things, as q is more general purpose and said is for situations when you want to be more specific.
