### ISSUE TITLE
Honorific inscription from Aphrodisias (working thread)

### ISSUE THREAD

**Issue by samosafuz** [SASDigitalHumanitiesTraining/TextEncoding#17]
<img width="1094" alt="Screen Shot 2021-05-19 at 11 36 34 AM" src="https://user-images.githubusercontent.com/61889129/118841788-9c311680-b896-11eb-9737-eaecf8ec35e1.png">

**Comment by samosafuz** [comment]
Here's a first pass at the teiHeader
```
        <fileDesc>
            <titleStmt>
                <title>Posthumous honours for ?Nikoteimos Hierax</title>
            </titleStmt>
            <publicationStmt>
                <authority>Inscriptions of Aphrodisias</authority>
                <idno type="iAph">iAph120003</idno>
            </publicationStmt>
            <sourceDesc>
                <msDesc>
                    <msIdentifier>
                        <repository>in situ</repository>
                    </msIdentifier>
                    <physDesc>
                        <objectDesc>
                            <supportDesc>
                                <support>
                                    <material>white marble</material>
                                    <dimensions unit="metre">
                                        <width>0.21</width>
                                        <height>0.38</height>
                                        <depth>0.22</depth>
                                    </dimensions>
<!--I'm not sure I have the conventional order of dimensions right, or whether I've mapped them accurately-->
                                        <objectType>right side of base</objectType>
                                </support>
                            </supportDesc>
                            <layoutDesc>
                                <layout>description of text field/campus</layout>
                            </layoutDesc>
                        </objectDesc>
                        <handDesc>
                            <handNote>description of letters, possibly including <height>letter-heights</height>
                            </handNote>
                        </handDesc>
                    </physDesc>
                    <history>
                        <origin>
                            <origPlace><placeName><settlement ref="https://pleiades.stoa.org/places/638753">Aphrodisias</settlement></placeName></origPlace>
                            <origDate notBefore="0001" notAfter="0100">First century AD</origDate>
                        </origin>
                        <provenance type="found" when="1893">
                            <placeName>
                                <settlement ref="https://pleiades.stoa.org/places/638753">Aphrodisias</settlement>
                            </placeName>
                            <p>Walls, North: fallen from the north wall of the Stadium</p>
                        </provenance>
                        <provenance type="observed" when="1961">
                            <placeName>
                                <settlement ref="https://pleiades.stoa.org/places/638753">Aphrodisias</settlement>
                            </placeName>
                            <p>Walls, North: fallen from the north wall of the Stadium</p>
                        </provenance>
                    </history>
                </msDesc>
            </sourceDesc>
        </fileDesc>
```

From experience with papyri, I placed the gazetteer `@ref` with `<provenance>` instead of `<origPlace>`. I was also surprised not to find this in the Trismegistos database, though it does appear in [PHI](http://epigraphy.packhum.org/inscriptions/oi?ikey=257189). Is there a reason for that?

**Comment by gabrielbodard** [comment]
I think Inscriptions of Aphrodisias use W x H x D, yes (we normally say so in the page—as [here](http://insaph.kcl.ac.uk/iaph2007/iAph010001.html)—but thanks to a bug in the markup that's missing from this one. Gazetteer reference looks good—it looks like you've tagged it in all three places, which is fine. (Although technically `origPlace` should point to an ancient place, and `provenance` to a modern place, e.g. in Geonames, that's not a distinction scholars conventionally stick to…) There might also be an urban gazetteer to which we could point for the "north walls".

**Comment by CarolineRichard** [comment]
![image](https://user-images.githubusercontent.com/84468763/119047444-38a20880-b9be-11eb-981c-93f9bfd15757.png)
Here is my little work. I am not really familiar with the encoding of non litterary stuff.
I had actually some doubts about the references, and I have the same problem in my own research : the text (or inscription or whatever) we encode is most of the time due to someone else's transcription or philological work. How and where do we indicate it : as a part of the sourcedesc ? Or the publicationStmt ? I first wanted to put it in the sourceDesc but didn't find how. 
It's the same for litterary texts : how do I put the editors of the text I use ?

**Comment by CarolineRichard** [comment]
```
<teiHeader>
      <fileDesc>
         <titleStmt>
            <title>Posthumous honours for <persName>?Nikoteimos Hierax</persName></title>
         </titleStmt>
         <publicationStmt>
          <authority>"Preliminary transcription (Reynolds); Gaudin; Kubitschek; publications This edition Roueché and Bodard (2007)."</authority>
           <idno ana="iAph">iAph120003</idno>
         </publicationStmt>
         <sourceDesc> 
            <msDesc>
               <msIdentifier>
                <placeName>Unknown</placeName>
               </msIdentifier>
               <physDesc>
                  <objectDesc>
                     <supportDesc>
                        <support>
                           <material>white marble</material>
                           <dimensions>
                           <depth>0.22</depth>
                           <height>0.38</height>
                           <width>0.21</width>
                           </dimensions>
                        </support>
                        <extent>12lines</extent>
                     </supportDesc>
                  </objectDesc>
               </physDesc>
               <history>
                  <origin>
                        <origDate>First century AD</origDate>
                        <placeName>Aphrodisias</placeName>
                        <origPlace>North, fallen from the north wall of the Stadium</origPlace>
                  </origin>
                  <provenance type="found" when ="1893">1961</provenance>
                  <acquisition>Published by Reinach, from Gaudin's squeeze, REG 19, 1906, 215, no. 103; by Cormack, from the MAMA records, MAMA 8, no. 483, whence McCabe PHI Aphrodisias</acquisition>
               </history>
            </msDesc>
         </sourceDesc>
      </fileDesc>
  </teiHeader>
  <text>
      <body>
         <p><lb n="1"/><supplied reason = "lost">ἡ βουλὴ καὶ ὁ δῆμο</supplied>ς̣ καὶ
<lb n="2"/><supplied unit="chars">ἡ γερουσία ἐτεί</supplied>μ̣ησαν
<lb n="3"/><supplied unit="chars">ταῖς πρώται</supplied>ς̣ τειμαῖς̣
<lb n="4"/><supplied unit="chars">Νεικότειμον Ἀρ</supplied>τεμιδώ-
<lb n="5"/><supplied unit="chars">ρου τοῦ Ζήνων</supplied>ος Ἱέρα-
<lb n="6"/><supplied unit="chars">κα ἄνδρα φιλόδ</supplied>ο̣ξον κα<supplied reason="unclear">[ὶ]</supplied>
<lb n="7"/><supplied unit="chars">φιλόπολιν γέ</supplied>νους πρώ-
<lb n="8"/><supplied unit="chars">του καὶ συνεκ</supplied>τικότος
<lb n="9"/><supplied unit="chars">τὴν πατρίδα γυ</supplied>μνασιαρ-
<lb n="10"/><supplied unit="chars">χήσαντα καὶ</supplied> ἑστιάσαν̣-
<lb n="11"/><supplied unit="chars">τα τὸν δῆμον</supplied> καὶτ<gap reason="lost" extent="unkown" unit="chars"/>
<lb n="12"/><gap extent="unknown" reason="lost" unit="lines"/> </p>
      </body>
  </text>
```
Sorry, the screenshot was not really readable ! Here it is.

**Comment by gabrielbodard** [comment]
@CarolineRichard : a couple of brief notes on your encoding.

- As far as I can see you are validating this file to the TEI All schema, which is fine, but you could get slightly more help with, e.g. constrained attribute values, if you used the EpiDoc schema (https://epidoc.stoa.org/schema/latest/)
- `<supplied reason="lost">` in line one is correct, but all of the other spans of restored text throughout the text should also have been `@reason="lost"` rather than `@unit="chars"` which is (a) a bit meaningless on supplied, and (b) not an attribute value recognised by EpiDoc (which would use "character")
- likewise on `<gap>` at the bottom of the text, `@unit="line"` is more correct EpiDoc (as opposed to the "lines" helpful suggested by TEI!)
- There seem to be a few underdots beneath letters in this edition; in EpiDoc these would be tagged `<unclear>x</unclear>` (and the underdots removed)

Nice work!

**Comment by CarolineRichard** [comment]
Thank you very much for commenting ! I modified my TEI file using the EpiDoc schema. 

>   <text>
      <body>
         <p><lb n="1"/><supplied reason = "lost">ἡ βουλὴ καὶ ὁ δῆμο</supplied><unclear>ς</unclear> καὶ
            <lb n="2"/><supplied reason ="lost">ἡ γερουσία ἐτεί</supplied><unclear>μ</unclear>ησαν
            <lb n="3"/><supplied reason="lost">ταῖς πρώται</supplied><unclear>ς</unclear>τειμαῖς̣
            <lb n="4"/><supplied reason="lost">Νεικότειμον Ἀρ</supplied>τεμιδώ-
            <lb n="5"/><supplied reason="lost">ρου τοῦ Ζήνων</supplied>ος Ἱέρα-
            <lb n="6"/><supplied reason="lost">κα ἄνδρα φιλόδ</supplied>ο<unclear>ξ</unclear>ον κα<supplied reason="lost">ὶ</supplied>
            <lb n="7"/><supplied reason="lost">φιλόπολιν γέ</supplied>νους πρώ-
            <lb n="8"/><supplied reason="lost">του καὶ συνεκ</supplied>τικότος
            <lb n="9"/><supplied reason="lost">τὴν πατρίδα γυ</supplied>μνασιαρ-
            <lb n="10"/><supplied reason="lost">χήσαντα καὶ</supplied> ἑστιάσα<unclear>ν</unclear>
            <lb n="11"/><supplied reason="lost">τα τὸν δῆμον</supplied> καὶτ<gap reason="lost" extent="unkown" unit="characters"/>
            <lb n="12"/><gap extent="unknown" reason="lost" unit="line"/> </p>
      </body>
  </text>
