### ISSUE TITLE
Transcription of Morpeth letter

### ISSUE THREAD

**Issue by NickSeager** [SASDigitalHumanitiesTraining/TextEncoding#19]
**Letter from Lord Morpeth to Mary Anne Rawson (English MS 415/112)**

							Grosvenor Place
						June 20. /34.

Madam,
	I am very much obliged to you for the Volume you have directed to be forwarded to me, which seems as prettily got up and promising in its contents as it is praiseworthy in its design.
	- The inherent self-complacency of an author cannot quite forbear from repining at a cruel mis-print;
The glowing bursts of glowing!!
		instead of glorious Song.
I must charitably wish that none of my associates have encountered any such mischief.
In spite of all printer’s devils, rightly I now see so [?]named, believe me, Madam,
	with sincere esteem,
		Your obliged Servt Morpeth

**Comment by PhillipsJ2** [comment]
Thank you Nick!

**Comment by rhoadsstevens** [comment]
Thank you! And I don't know if this is helpful, but this is a TEI project that features diary entries:

https://github.com/eba-diary

I was thinking about trying to encode this letter somewhat in the same way.

---Elliott

**Comment by gabrielbodard** [comment]
Has anyone taken a first bash at tagging the structure of this letter yet?

**Comment by rhoadsstevens** [comment]
Going to work on this this afternoon Seattle time. Looking forward to seeing how others approach the letter.

Elliott

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by strill66** [comment]
Dear all, I believe the link below will allow access to a tagged version of the letter (I haven't included metadata, but have added in some 'corresDesc' info.

https://uoe-my.sharepoint.com/:u:/g/personal/strill_ed_ac_uk/ERpU-BHEdWdMopRQhzbW3EkBTEvo4dlVmmqZK2PiStkxTg?e=sKlKwD

**Comment by EmilieMtrn** [comment]
Hello,
I'm starting from scratch as regards XML and TEI, so here is my humble contribution. 
Hope the link works!
https://drive.google.com/file/d/1b447NikaWupbP0Yu34E_PExbf6SQmYei/view?usp=sharing

**Comment by michaeldcohen** [comment]
Here's my first pass at adding a few tags to the letter. Did anyone else find that, in oXygen, `<profileDesc><correspDesc>` had to be added manually? Was I mistaken in understanding that it was part of the default header in the current version of TEI?

![image](https://user-images.githubusercontent.com/84543477/119046451-52255f00-b982-11eb-819b-0e4d7ecf867e.png)

**Comment by rhoadsstevens** [comment]
This was fun! Great work, Michael and Emilie. This is what I did--though I didn't go any beyond what Christopher demonstrated in that video:
https://drive.google.com/drive/folders/1o9Q6gZbiCfyw8gnJLZbRs3B5XGS7z1aF?ths=true

**Comment by rhoadsstevens** [comment]
This Van Gogh Reader site has lots of encoding with TEI in it, and I was comparing how they encoded the Van Gogh letters with what we did. Here is where you can find that TEI:

http://vangoghletters.org/vg/about_6.html

**Comment by RobbKH** [comment]
Thanks Nick!

**Comment by RobbKH** [comment]
Thanks everyone for sharing your work! Here is my first stab at the text section of the document.

</teiHeader>
  <text>
      <body>
         <opener><dateline><geogName>Grosvenor Place</geogName>
            <date when="1834-06-20">June 20. /34</date></dateline>
            <salute>Madam,</salute></opener>
         <p><lb/>
            <lb/><rs>I</rs> am very much obliged to <rs>you</rs> 
            <lb/>for the Volume <rs>you</rs> have 
            <lb/>directed to be forwarded to <rs>me</rs>, 
            <lb/>which seems as prettily got up 
            <lb/>and promising in its contents as it is praiseworthy in its design.</p>
            <p><lb/>- The inherent self-complacency 
            <lb/>of an author cannot quite forbear 
            <lb/>from repining at a cruel mis-print;</p>
            <p><lb/>The glowing bursts of glowing!! 
            <lb/>instead of glorious Song.</p>
            <p><lb/><rs>I</rs> must charitably wish that none 
            <lb/>of <rs>my</rs> associates have encountered 
            <lb/>any such mischief.</p>
            <p><lb/>In spite of all printer’s <orig>d-v-ls</orig><reg>devils</reg>, rightly 
            <lb/><rs>I</rs> now see so named,</p>
         <closer>,<salute><lb/>believe <rs>me</rs>, Madam,
            <lb/>with sincere esteem,
            <lb/>Your obliged Servt,</salute><signed><persName>Morpeth</persName></signed></closer>
      </body>
  </text>
</TEI>

**Comment by PhillipsJ2** [comment]
Hi all,

This is my attempt at encoding the letter and adding as much metadata as I could:

https://gla-my.sharepoint.com/:u:/g/personal/j_phillips_3_research_gla_ac_uk/EW62QU2bMP5Oov1NE-6VeiUBtre3W7zBdUInoURw6zEgrQ?e=HTg9VS

Josh

**Comment by cmohge1** [comment]
> Here's my first pass at adding a few tags to the letter. Did anyone else find that, in oXygen, `<profileDesc><correspDesc>` had to be added manually? Was I mistaken in understanding that it was part of the default header in the current version of TEI?
> 
> ![image](https://user-images.githubusercontent.com/84543477/119046451-52255f00-b982-11eb-819b-0e4d7ecf867e.png)

Nice work! You're right that `<profileDesc>` and `<correspDesc>` have to be added to the TEI template. The default header does not include `<profileDesc>` because it is not required for all TEI documents, so you would need to add that for other kinds of metadata, not just `<correspDesc>` but also `<listPerson>` and so on.

**Comment by cmohge1** [comment]
> Hello,
> I'm starting from scratch as regards XML and TEI, so here is my humble contribution.
> Hope the link works!
> https://drive.google.com/file/d/1b447NikaWupbP0Yu34E_PExbf6SQmYei/view?usp=sharing

Solid work -- thanks for sharing. It was good that you made use of `<!--commenting-->` in your xml for an unclear word, but I also wanted to let you know that you can also tag an unclear word with an `<unclear>` element (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-unclear.html).

**Comment by strill66** [comment]
I can't access Josh's file - were others able to access mine? Also, I think I inadvertently saved it in brackets rather than oygen. And, yes, I found you had to add profile/corresDescs, Suzanne

**Comment by cmohge1** [comment]
> This Van Gogh Reader site has lots of encoding with TEI in it, and I was comparing how they encoded the Van Gogh letters with what we did. Here is where you can find that TEI:
> 
> http://vangoghletters.org/vg/about_6.html

Thanks -- the van Gogh letters are an exemplary project indeed.

**Comment by RobbKH** [comment]
Here is my first stab at the body section of the Morpeth letter.

https://drive.google.com/file/d/1sjIXYtydBmvH8mqMLAKGcyw0HCQ6B5FI/view?usp=sharing
