### ISSUE TITLE
Intro to Text Encoding: Introduce yourself

### ISSUE THREAD

**Issue by gabrielbodard** [SASDigitalHumanitiesTraining/TextEncoding#21]
Please tell us briefly in this thread who you are and what is your interest in text encoding.

**Comment by bfiliks** [comment]
I am Felix Oke, an MA student of Digital Humanities. I am interested in TEX for the digital edition.

**Comment by Treschow** [comment]
Hey, I'm Michael Treschow, wanting to develop a digital critical edition of the Old English Soliloquies. Have a little TEI training from years ago. Need a refresher.

**Comment by marimccarville** [comment]
Hello! My name is Mari McCarville, and I am just beginning to build a digital archive. I am interested in using TEI for archiving historical manuscripts.

**Comment by ttsiampokalos** [comment]
Hi, I'm Fanis Tsiampokalos, a classicist at the University of Trier, Germany. I'm interested in TEI for editing historical texts.

**Comment by AgneseDAngelo** [comment]
Hello! I'm Agnese D'Angelo, I'm a PhD student at Sapienza University (Rome). I'm interested in TEI for editing _marginalia._

**Comment by NCLivengood** [comment]
Hello! I am Nicole Livengood. I am looking to broaden my skills in the digital humanities, for teaching and scholarly purposes.

**Comment by ththomas** [comment]
Hi! I am Theodore THOMAS from University of Athens and I am interested in TEI for archiving literary manuscripts.

**Comment by luchretius** [comment]
Hi! I’m Christopher Lu, and I am a recent MA graduate from the Warburg Institute. I will pursue a degree in Classics at Oxford in September. Like Agnese, I’m interested in _marginalia_ and would like to have TEI under my belt for future projects.

**Comment by catgower** [comment]
Hi, I'm Cat. I'm a second-year PhD student at Nottingham Trent University. My research project looks at genealogical chronicles produced under Henry VI. Genealogical chronicles tend to contain a lot of names, locations, dates, and familial connections so being able to encode this type of data throughout would be beneficial for producing digital editions of such works.

**Comment by davideibeck** [comment]
Hi, I'm David Eibeck and I'm a master student in ancient history. I work as a student assistant at the universities of Stuttgart and Mainz and in the latter I'm currently working on a digital edition database of latin inscriptions. So I already have some experience with EpiDoc, but repetita iuvant and I surely will learn a lot of new aspects!

**Comment by mgbilby** [comment]
Hi, I'm Mark Bilby. ScholComm Librarian and Religious Studies lecturer at Cal State Fullerton. I'd like to improve my Digital Humanities skills and incorporate TEI XML knowledge into my research on ancient gospels (canonical and non-canonical) and computational linguistics.

**Comment by yunfeyang2** [comment]
Hi, I'm Yunfei Yang, an MPhil student at the Department of Chinese and History in the City University of HK. My research interest is about the historiography in the Song dynasty (960-1279), so the text is the core of my concern. I hope the learning of TEI can help with my research.

**Comment by cmanco1** [comment]
Hello! I'm Caterina Manco, I have a PhD in Classics. I'm interested in TEI for editing a text on ancient pharmacology.

**Comment by kaylendwyer** [comment]
Hi, I'm Kaylen Dwyer. I recently gained my MLIS and I work at the the Institute for Digital Research in the Humanities at the University of Kansas. I am interested in how TEI can be used for intertextual studies.

**Comment by s0crates2** [comment]
Hello, I'm Greta Boers, Librarian for Classical Studies at Duke University.  I wanted to learn more about TEI, hands-on, to better support the digital humanities projects of our faculty and students.  If I understand the available methods for analyzing and mining texts, I hope I'll be better at  finding good  sources.  Also, it will help me understand more of the interesting conversations on the Digital Classicist list!

**Comment by mpignot** [comment]
Hi, I'm Matthieu Pignot, Leverhulme Early Career Fellow in History at Durham University. I'm working on early medieval manuscripts of the works of Augustine of Hippo and I'm interested in learning more about XML TEI in particular to encode metadata about manuscripts. I would also like to produce digital editions of lesser known, anonymous late antique texts.

**Comment by SherlockSidekick** [comment]
Hello, everyone. I'm Ben Watson. I'm a professor at the University of Oklahoma, and I am editing lengthy prose texts. TEI seems to offer the best way of keeping my apparatus with my text (and it looks like it's going to allow me to include even more information that a typical app. crit. would.)
