### ISSUE TITLE
Question about TEI Core Modeling Slides "Numbers and Measures" 

### ISSUE THREAD

**Issue by s0crates2** [SASDigitalHumanitiesTraining/TextEncoding#23]
I don't know whether this is a coding question or a math question! This is from the slides about numbers and measures in the Core Modeling presentation.  Why are the numbers "804672" and "160934" different in the example below, since the unit measures in both sections are miles? Or, if they are meant to refer to one another, why are they not  `<measureGrp>` ?

`<l>
	But I would walk
	<measure quantity=”804672” type=”distance” unit= ”m”>
		500 miles
	</measure>
</l>
`

`<l>
	Just to be the man who walks
	<measure quantity=”160934” type=”distance” unit= ”m”>
		a thousand miles
	</measure>
</l>
`

Thanks, 
Greta

**Comment by cmohge1** [comment]
Great question--the `@who="m"` attribute is normalising values in meters (although the second `@quantity` value is a typo--it should be 1609344!). In any case, the idea is that you can normalise alternate forms of written measurements in the TEI `<measure>` elements. This become very important when dealing with archaic sources.

**Comment by s0crates2** [comment]
Ahh! That makes sense! It's a math question after all.    I had wondered whether it was some kind of calibration for the measurement  of miles, but then I couldn't figure out why 500  (804672) was less than a 1000 (160934).  Thank you!.
