### ISSUE TITLE
What does ((stop)) mean in a transcription? 

### ISSUE THREAD

**Issue by s0crates2** [SASDigitalHumanitiesTraining/TextEncoding#25]
Sorry to bother you yet again!!  I chose the Latin decree from Ptolemais for my exercise. I addition to the expected expressions for missing text like  [---] or [c. 7 - 8] the text also has ((stop)) in the middle. What is that? I've looked on EpiDoc and other documentation for variations of the Leiden Conventions, but no luck. 

[c. 12]ssunt ((stop)) deduca[--- Cn(aeus) Cornelius]
[Lent]ulus ((stop)) P(ubli) ((stop)) f(ilius) Marcelleinus ( vac. 1) le[gatus pro pr(aetore) --- Cn(aei) Pompeii Magni]
[im]peratoris ((stop)) ṭẹṛṭịo ( vac. 1) praedia ((stop)) [---]

Thanks.

**Comment by s0crates2** [comment]
Never mind, I found the answer.

**Comment by gabrielbodard** [comment]
Could we keep this ticket open and post the answer here, as I'm sure others will find it useful too?

**Comment by s0crates2** [comment]
Yes, please.  I asked some of my local colleagues who explained that there is such a thing as an interpunct in Latin-- which I didn't know-- and that there are variations to note this across conventions, so I couldn't easily find this one. However,  there's a larger and valuable question about discovery! Thank you!

**Comment by gabrielbodard** [comment]
I think in this case the epigraphic editor is simply indicating that there is a dot, point, or stop at this point in the text, without specifying that it is an interpunct or any specific type of punctuation. The correct way to encode this in EpiDoc is very slightly more complicated than most things:

(1) You need an authority list (internal or external, but for this example let's assume internal) defining types of non-alphanumeric characters that may appear in your corpus:

~~~~
<charDecl>
    <glyph xml:id="stop">
        <mapping type="standard">•</mapping>
        <mapping type="simplified">(stop)</mapping>
    </glyph>
</charDecl>
~~~~

(2) where the stop (or any other symbol) appears in the text, tag it as a `<g>` pointing to the glyph in the authority list:

`<g ref=#stop"/>`

**Comment by s0crates2** [comment]
Thank you!

**Comment by gabrielbodard** [comment]
I meant to link the [EpiDoc Guidelines page](https://epidoc.stoa.org/gl/latest/trans-symbol.html) for this feature btw.
