### ISSUE TITLE
Technical help with markup exercise

### ISSUE THREAD

**Issue by gabrielbodard** [SASDigitalHumanitiesTraining/TextEncoding#3]
If you have any technical or practical issues with the markup exercise, please write about them in this thread. You may also keep an eye on this thread in case you are able to help any of your colleagues with an issue you were able to resolve yourself.

**Comment by hannah-sonbol** [comment]
Dear all, 
I am having some difficulty with running the "Markdown Preview Enhance" package. According to another forum, one should de-active the normal one "Markdown Preview", which I also did and it changed nothing.

I also added ##s, **s and []s, but it changes nothing, not even the color.

Help would be much appreciated. Thank you very much,
Hannah

**Comment by mathildebru** [comment]
Hi Hannah- for the long s I found typing &#383; works (it's the HTML letter symbol). 
I found I didn't have to deactivate anything to use the markdown-preview-enhanced package- I just followed exactly what Christopher did in the introduction video to install it on Atom.

**Comment by mathildebru** [comment]
'&#383;' is what you have to type in for the &#383; (just without the '')

**Comment by mathildebru** [comment]
https://www.toptal.com/designers/htmlarrows/letters/

**Comment by gabrielbodard** [comment]
@hannah-sonbol could you tell us which platform you're running this in? (Windows, Mac, etc.) I don't know how easy this will be to troubleshoot remotely.

In the meantime, have you tried doing the exercise in Dillinger, so you can at least make a start?

**Comment by hannah-sonbol** [comment]
Thank you dear Mathilde!

as for the computer: I am using Mac; but yes, I have thought of eventually trying it another program.

**Comment by FlannelBanshee** [comment]
How have you guys solved the long vertical line for REMARKS? Is it a table and having just the middle line showing somehow, maybe?

**Comment by daria-drozdova** [comment]
I have installed Atom + markdown preview. And I have also Markdown Editor and MultiMarkdown Composer on my Mac. And I have different visualizations of the same markdown text. Why is it happening?

**Comment by Orpheus22** [comment]
@hannah-sonbol did you toggle the settings for your file, so that it's using not Plain Text, but Github Markdown? That allowed my file to show the right colors for indication of the markup.

**Comment by cmohge1** [comment]
Thanks, all. Just to be clear, the Atom package is 'markdown-preview-enhanced'. Once it is installed it should work on the most recent version of Atom (by toggling control + shift + m), and, as @Orpheus22 says, you need to make sure that your file is saved with the .md extension so that the system knows it is a Markdown file. As I said yesterday, if Atom is not working for you, you could use https://dillinger.io/, which is a reliable web application. Atom is a community-based software, so there are some bugs occasionally :)

**Comment by cmohge1** [comment]
Sorry, one more thing: another way to encode the long s is to use unicode hex codes that all browsers would recognise, e.g.:

&#x17f;&#x17f;

See https://www.codetable.net/hex/17f

**Comment by gabrielbodard** [comment]
@FlannelBanshee:
> How have you guys solved the long vertical line for REMARKS? Is it a table and having just the middle line showing somehow, maybe?

Another question is whether you need to have remarks in two columns in the first place? (I wouldn't know how to display the vertical line in the table using Markdown, although in HTML+CSS it would be easy enough.)

**Comment by gabrielbodard** [comment]
@daria-drozdova: 
> I have installed Atom + markdown preview. And I have also Markdown Editor and MultiMarkdown Composer on my Mac. And I have different visualizations of the same markdown text. Why is it happening?

It's hard to say without seeing your visualisations (could you post screenshots?) but in general it's worth noting that there are several implementations of Markdown with slightly different models and syntaxes, so you might expect to see small variations. (If you look for variations of "Wikitext" you'll see even more varieties of the same general principal, many of which are completely incompatible with one another.) The broad principles of **bold** and _Italic_ and [links]() are broadly coalescing, but more esoteric details such as footnotes are likely to vary more wildly.

**Comment by jbrown60** [comment]
I am also having problems in toggling views in Atom and switching to preview. I installed the 'markdown-preview-enhanced' package but the commands don't seem to do anything. When I click on 'packages' > 'markdown preview', the command keys appear 'ghosted', showing it is not available (screenshot attached). 

[
![Screen Shot 2020-11-25 at 12 25 59 pm](https://user-images.githubusercontent.com/71740356/100170559-d90aea80-2ebd-11eb-91b0-51f1a23b1067.png)
](url)

**Comment by MarkQUB** [comment]
I'm new to this area and am still trying to get to grips with some of the technology. I found markdown very easy to use and got the hang of it pretty quickly. I wonder could someone point me in the direction of a HTML text editor so I can have a look at that or can that also be done via Atom?

**Comment by MelitaThomas** [comment]
I'm a complete beginner. I am working through the Markdown Tutorial, but when I try to make a new paragraph in the tutorial with <p> and end it with </p> it does not work - the markdown preview just shows rogue characters as below. 

<p>&lt;p&gt;The sky above the port was the color of television, tuned to a dead channel.&lt;/p&gt;&lt;p&gt; It was a bright cold day in April, and the clocks were striking thirteen.&lt;\p&gt;</p>

Can anyone tell me what am I doing wrong?

**Comment by gabrielbodard** [comment]
@jbrown60:
> I am also having problems in toggling views in Atom and switching to preview. I installed the 'markdown-preview-enhanced' package but the commands don't seem to do anything. When I click on 'packages' > 'markdown preview', the command keys appear 'ghosted', showing it is not available (screenshot attached).

Are you sure you have saved your file as Markdown (suffix .md) when you try to do this? It has to know it's looking at Markdown to be able to preview.

**Comment by gabrielbodard** [comment]
@MarkQUB: 
> I'm new to this area and am still trying to get to grips with some of the technology. I found markdown very easy to use and got the hang of it pretty quickly. I wonder could someone point me in the direction of a HTML text editor so I can have a look at that or can that also be done via Atom?

Yes, you can also edit HTML directly in Atom. Just save your file with the suffix .html so it knows to treat it as HTML. Then if you double click on the file on your desktop, it should preview it for you in a web browser.

**Comment by gabrielbodard** [comment]
@MelitaThomas: 
> it does not work - the markdown preview just shows rogue characters as below.
> <p>The sky above the port was the color of television, tuned to a dead channel.</p><p> It was a bright cold day in April, and the clocks were striking thirteen.<\p>

It looks like in your second paragraph you are closing it with `<\p>` instead of `</p>` (the direction of the slash matters!). Does that fix it?

**Comment by MelitaThomas** [comment]
> 
> 
> @MelitaThomas:
> 
> > it does not work - the markdown preview just shows rogue characters as below.
> > The sky above the port was the color of television, tuned to a dead channel. It was a bright cold day in April, and the clocks were striking thirteen.<\p>
> 
> It looks like in your second paragraph you are closing it with `<\p>` instead of `</p>` (the direction of the slash matters!). Does that fix it?

I think I have been muddling markdown and html up in answering the exercises.  Working better now. Thanks.

**Comment by MelitaThomas** [comment]
Sorry to ask a basic question, but how do you indent a row?

**Comment by aghague** [comment]
Hi - Does this forum support nested replies? I'd like to contribute to a couple of the stands here, but I'm not sure how best to signal with which specific post I am engaging at any given time. Thanks!

**Comment by aghague** [comment]
> @FlannelBanshee:
> 
> > How have you guys solved the long vertical line for REMARKS? Is it a table and having just the middle line showing somehow, maybe?
> 
> Another question is whether you need to have remarks in two columns in the first place? (I wouldn't know how to display the vertical line in the table using Markdown, although in HTML+CSS it would be easy enough.)

My understanding is that we'd use markdown to make the content accessible to other users (human or machine) who would  engage in further processing, so my take on the vertical issue is that we need not worry about preserving it. If unsure about the importance of the layout, maybe one could comment the code? Not that I know yet how one inserts comments in Markdown - but I'm sure there's an FAQ/tutorial for this somewhere.

**Comment by aghague** [comment]
> > @FlannelBanshee:
> > > How have you guys solved the long vertical line for REMARKS? Is it a table and having just the middle line showing somehow, maybe?
> > 
> > 
> > Another question is whether you need to have remarks in two columns in the first place? (I wouldn't know how to display the vertical line in the table using Markdown, although in HTML+CSS it would be easy enough.)
> 
> My understanding is that we'd use markdown to make the content accessible to other users (human or machine) who would engage in further processing, so my take on the vertical line issue is that we need not worry about preserving it. My general approach to things I'm forced to skip or alter in terms of layout is to insert editorial comments, so my instinct is to carry this into code. Not that I know yet how one inserts comments in Markdown, mind - but I'm sure there's an FAQ/tutorial for this somewhere.

Found a guide to commenting in Markdown: https://www.jamestharpe.com/markdown-comments/ Seems to work.

**Comment by aghague** [comment]
> Dear all,
> I am having some difficulty with running the "Markdown Preview Enhance" package. According to another forum, one should de-active the normal one "Markdown Preview", which I also did and it changed nothing.
> 
> I also added ##s, **s and []s, but it changes nothing, not even the color.
> 
> Help would be much appreciated. Thank you very much,
> Hannah

Hi Hannah - are you using Windows? I haven't had much luck with the enhanced preview in Atom either (I'm running Windows 10 Pro on a Surface Book 2), so I've switched to Visual Studio.  I don't fully remember the set-up process, but I think you might have to install a local instance of Git as well for the preview to run. The good news is that that's not as complicated as it might sound:  VS prompts you to do so and provides a handy link to the download. The bad news is that the preview icon is small and not immediately suggestive of rendered output, so you may have to hunt around a bit to find it; it's in the top right-hand corner of the file editor window, next to the 'split editor' icon. I think you may also have to restart VS once you install Git, but I'm not sure about that. Hope this helps!

**Comment by cmohge1** [comment]
> Sorry to ask a basic question, but how do you indent a row?

@MelitaThomas Markdown does not currently support indentation. Best to do indentation in the html by adding CSS––e.g. 

`text-indent: -2em;`

You could either intend particular lines with 

`<p style="text-indent: -2em;">`

or create a CSS file that automatically intends all p tags.

See https://www.w3schools.com/csSref/pr_text_text-indent.asp
